# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import getscore_pb2 as getscore__pb2


class HuScoreStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckHuType = channel.unary_unary(
                '/getscore.HuScore/CheckHuType',
                request_serializer=getscore__pb2.CardInfo.SerializeToString,
                response_deserializer=getscore__pb2.checkTypeScore.FromString,
                )


class HuScoreServicer(object):
    """The greeting service definition.
    """

    def CheckHuType(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HuScoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckHuType': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHuType,
                    request_deserializer=getscore__pb2.CardInfo.FromString,
                    response_serializer=getscore__pb2.checkTypeScore.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'getscore.HuScore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HuScore(object):
    """The greeting service definition.
    """

    @staticmethod
    def CheckHuType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/getscore.HuScore/CheckHuType',
            getscore__pb2.CardInfo.SerializeToString,
            getscore__pb2.checkTypeScore.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
