# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getscore.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='getscore.proto',
  package='getscore',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0egetscore.proto\x12\x08getscore\"\xb4\x03\n\x08\x43\x61rdInfo\x12\x36\n\ntypeMapAll\x18\x01 \x03(\x0b\x32\".getscore.CardInfo.TypeMapAllEntry\x12\x10\n\x08tilesNum\x18\x02 \x01(\x05\x12\x10\n\x08\x64iscards\x18\x03 \x03(\x03\x12\x11\n\thandCards\x18\x04 \x03(\x03\x12\x14\n\x0csurplusCards\x18\x05 \x03(\x03\x12\x12\n\notherHands\x18\x06 \x03(\x03\x12\x11\n\tchowCards\x18\x07 \x03(\x03\x12\x11\n\tpongCards\x18\x08 \x03(\x03\x12\x10\n\x08mingKong\x18\t \x03(\x03\x12\x0e\n\x06\x61nKong\x18\n \x03(\x03\x12\x10\n\x08isBanker\x18\x0b \x01(\x08\x12\x0e\n\x06isZimo\x18\x0c \x01(\x08\x12\x0f\n\x07robKong\x18\r \x01(\x08\x12\x15\n\rlastOptIsKong\x18\x0e \x01(\x08\x12\x14\n\x0clastCard_cpk\x18\x0f \x01(\x08\x12\x10\n\x08lastCard\x18\x10 \x01(\x03\x12\x11\n\ttableFeng\x18\x11 \x01(\x03\x12\x0f\n\x07menFeng\x18\x12 \x01(\x03\x1a\x31\n\x0fTypeMapAllEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"x\n\x0e\x63heckTypeScore\x12\x36\n\x07message\x18\x01 \x03(\x0b\x32%.getscore.checkTypeScore.MessageEntry\x1a.\n\x0cMessageEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32H\n\x07HuScore\x12=\n\x0b\x43heckHuType\x12\x12.getscore.CardInfo\x1a\x18.getscore.checkTypeScore\"\x00\x62\x06proto3'
)




_CARDINFO_TYPEMAPALLENTRY = _descriptor.Descriptor(
  name='TypeMapAllEntry',
  full_name='getscore.CardInfo.TypeMapAllEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='getscore.CardInfo.TypeMapAllEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='getscore.CardInfo.TypeMapAllEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=465,
)

_CARDINFO = _descriptor.Descriptor(
  name='CardInfo',
  full_name='getscore.CardInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='typeMapAll', full_name='getscore.CardInfo.typeMapAll', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tilesNum', full_name='getscore.CardInfo.tilesNum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='discards', full_name='getscore.CardInfo.discards', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='handCards', full_name='getscore.CardInfo.handCards', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='surplusCards', full_name='getscore.CardInfo.surplusCards', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='otherHands', full_name='getscore.CardInfo.otherHands', index=5,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chowCards', full_name='getscore.CardInfo.chowCards', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pongCards', full_name='getscore.CardInfo.pongCards', index=7,
      number=8, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mingKong', full_name='getscore.CardInfo.mingKong', index=8,
      number=9, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anKong', full_name='getscore.CardInfo.anKong', index=9,
      number=10, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isBanker', full_name='getscore.CardInfo.isBanker', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isZimo', full_name='getscore.CardInfo.isZimo', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robKong', full_name='getscore.CardInfo.robKong', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastOptIsKong', full_name='getscore.CardInfo.lastOptIsKong', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastCard_cpk', full_name='getscore.CardInfo.lastCard_cpk', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastCard', full_name='getscore.CardInfo.lastCard', index=15,
      number=16, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tableFeng', full_name='getscore.CardInfo.tableFeng', index=16,
      number=17, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='menFeng', full_name='getscore.CardInfo.menFeng', index=17,
      number=18, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CARDINFO_TYPEMAPALLENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=465,
)


_CHECKTYPESCORE_MESSAGEENTRY = _descriptor.Descriptor(
  name='MessageEntry',
  full_name='getscore.checkTypeScore.MessageEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='getscore.checkTypeScore.MessageEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='getscore.checkTypeScore.MessageEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=587,
)

_CHECKTYPESCORE = _descriptor.Descriptor(
  name='checkTypeScore',
  full_name='getscore.checkTypeScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='getscore.checkTypeScore.message', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CHECKTYPESCORE_MESSAGEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=587,
)

_CARDINFO_TYPEMAPALLENTRY.containing_type = _CARDINFO
_CARDINFO.fields_by_name['typeMapAll'].message_type = _CARDINFO_TYPEMAPALLENTRY
_CHECKTYPESCORE_MESSAGEENTRY.containing_type = _CHECKTYPESCORE
_CHECKTYPESCORE.fields_by_name['message'].message_type = _CHECKTYPESCORE_MESSAGEENTRY
DESCRIPTOR.message_types_by_name['CardInfo'] = _CARDINFO
DESCRIPTOR.message_types_by_name['checkTypeScore'] = _CHECKTYPESCORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CardInfo = _reflection.GeneratedProtocolMessageType('CardInfo', (_message.Message,), {

  'TypeMapAllEntry' : _reflection.GeneratedProtocolMessageType('TypeMapAllEntry', (_message.Message,), {
    'DESCRIPTOR' : _CARDINFO_TYPEMAPALLENTRY,
    '__module__' : 'getscore_pb2'
    # @@protoc_insertion_point(class_scope:getscore.CardInfo.TypeMapAllEntry)
    })
  ,
  'DESCRIPTOR' : _CARDINFO,
  '__module__' : 'getscore_pb2'
  # @@protoc_insertion_point(class_scope:getscore.CardInfo)
  })
_sym_db.RegisterMessage(CardInfo)
_sym_db.RegisterMessage(CardInfo.TypeMapAllEntry)

checkTypeScore = _reflection.GeneratedProtocolMessageType('checkTypeScore', (_message.Message,), {

  'MessageEntry' : _reflection.GeneratedProtocolMessageType('MessageEntry', (_message.Message,), {
    'DESCRIPTOR' : _CHECKTYPESCORE_MESSAGEENTRY,
    '__module__' : 'getscore_pb2'
    # @@protoc_insertion_point(class_scope:getscore.checkTypeScore.MessageEntry)
    })
  ,
  'DESCRIPTOR' : _CHECKTYPESCORE,
  '__module__' : 'getscore_pb2'
  # @@protoc_insertion_point(class_scope:getscore.checkTypeScore)
  })
_sym_db.RegisterMessage(checkTypeScore)
_sym_db.RegisterMessage(checkTypeScore.MessageEntry)


_CARDINFO_TYPEMAPALLENTRY._options = None
_CHECKTYPESCORE_MESSAGEENTRY._options = None

_HUSCORE = _descriptor.ServiceDescriptor(
  name='HuScore',
  full_name='getscore.HuScore',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=589,
  serialized_end=661,
  methods=[
  _descriptor.MethodDescriptor(
    name='CheckHuType',
    full_name='getscore.HuScore.CheckHuType',
    index=0,
    containing_service=None,
    input_type=_CARDINFO,
    output_type=_CHECKTYPESCORE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HUSCORE)

DESCRIPTOR.services_by_name['HuScore'] = _HUSCORE

# @@protoc_insertion_point(module_scope)
